Fix GIL protection with CVirtualHelper
mhammond/pywin32 pull request #1657
Opened 2021-01-28 21:03 UTC by kxrob

GIL issues noticed during debugging of win32ui GUI code with threading.

2021-03-27 03:00 UTC, mhammond commented
Sorry that this slipped through the cracks. Can you explain in more detail what problem this fixes? Given this touches so much code I'm surprised the flaws in the existing implementation aren't immediately obvious.

2021-09-07 12:21 UTC, kxrob commented
> Can you explain in more detail what problem this fixes? Given this touches so much code I'm surprised the flaws in the existing implementation aren't immediately obvious.

Rebased and updated descriptions.
Those recent changes  3c9271d + 27a1ae8  introduced (more) Python API calls being possible outside GIL. Corruptions happen rarely with threads + win32ui only.
The 1st main commit is small, and removes more explicit CEnterLeavePython's than adding code.
The 2nd is only for further (optional) optimizations to reduce GIL time a little more - via some early routine helper.release_full() 's.

2021-09-08 05:23 UTC, mhammond requested changes
This looks fine to me, thanks - please just remove some of the commented lines and I'll commit it.

2021-09-08 05:23 UTC, mhammond commented on Pythonwin/ddeserver.cpp
> +        //CEnterLeavePython _celp;
Please delete lines rather than commenting them out (also below, but I haven't commented against them all)

2021-09-08 12:34 UTC, kxrob commented on Pythonwin/ddeserver.cpp
> +        //CEnterLeavePython _celp;
Done

2021-09-09 08:52 UTC, mhammond approved these changes

2021-09-09 08:52 UTC, merged