Update and rename file.d to file.html
mhammond/pywin32 pull request #1714
Opened 2021-06-11 23:40 UTC by arihant2math

Changed the doc to html

2021-06-17 04:00 UTC, mhammond requested changes
Thanks! However, the `.d` files are processed by autoduck and included in the .chm help file shipped with the distribution, so most of the changes there should be undone. It would be great if we could work out how to get the generated .html and put that up somewhere, but for now just the typos etc in that file should be changed

2021-06-18 21:37 UTC, arihant2math commented
@mhammond I fixed that now.

2021-06-24 07:29 UTC, mhammond reviewed
Thanks for the update, but I'd like to understand why you are touching file.d at all?

2021-06-24 07:29 UTC, mhammond commented on win32/help/file.d
> -
Have you checked how this now renders? I'm worried that removing many of these blank lines will hurt readability - especially between human text and examples. What is your motivation for touching this file at all?

2021-06-28 17:37 UTC, arihant2math commented
@mhammond any update on this?

2021-06-28 17:42 UTC, arihant2math commented
I reverted the commits

2021-07-02 05:18 UTC, arihant2math commented
@mhammond Any updates on this?

2021-07-02 05:28 UTC, closed without merging