Release GIL when creating or starting a service
mhammond/pywin32 pull request #2062
Opened 2023-05-31 16:22 UTC by adamkbmc

Some service take a while to start so this change releases the GIL so that the python process isn't blocked. It only applies to CreateService and StartService. I guess it could also be applied to ControlService and DeleteService but these are simple calls into the Win32 API (and we've not had a problem with services taking a long time to stop or when being deleted)

It also has a small build change: on some machines (generally developer systems) the default action for a .py file isn't to run it, but to edit it. If the default action has been changed then the build breaks so my change just runs the h2py.py script using python.exe explicitly. This seems to be the only place where .py files are run without specifying the interpreter

2023-05-31 16:42 UTC, mhammond requested changes
The service changes look fine, but please split the makefile change into a different PR, as that might break other workflows

2023-05-31 16:43 UTC, mhammond commented
Maybe add a note to the changelog too?

2023-06-05 11:04 UTC, adamkbmc commented
I've added a note to CHANGES.txt and backed out the makefile_pythonwin change. I didn't plan to submit that at the same time I just needed it to make the code build on my machine.

2023-06-07 20:56 UTC, mhammond approved these changes
Thanks!

2023-06-07 20:56 UTC, merged