Change `mbcs` encoding to `utf-8`
mhammond/pywin32 pull request #2097
Opened 2023-08-09 19:09 UTC by Avasam

https://github.com/mhammond/pywin32/pull/1990#discussion_r1288601998
> [...] I suspect this is wrong now - when this file is being read I believe it will be assumed utf-8. Ditto the mbcs reference in build.py

\- @mhammond 

This changes more than what the initial comment mentioned, but I figured may as well review all usages of it. Even if we end up reverting because the needed changes would be too big.

2023-08-09 19:11 UTC, Avasam commented on win32/Demos/win32gui_dialog.py
>                      # LVM_SETITEMW etc.
> # Note this demo still works with byte strings.  An
> # alternate strategy would be to use unicode natively
> # and use the 'W' version of the messages - eg,

For instance this comment leads me to believe it won't be as simple as changing the encoding, unless it was specific to Python 2 ?

2023-08-10 17:02 UTC, mhammond requested changes
I think for now we should only change the COM functions - where we generate a .py file. Most of the other places changed are quite possibly wrong as it's not Python file IO consuming the bytes.

2023-08-10 17:02 UTC, mhammond commented on Pythonwin/pywin/tools/hierlist.py
> +        ##  text = text.encode("utf-8")
These lines should just be removed.

2023-08-10 17:02 UTC, mhammond commented on isapi/install.py
> +        server_desc = server_desc.decode("utf-8")
as the comment notes, the source of this is sys.argv - is that now guaranteed to be utf-8? I suspect not.

2023-08-10 17:12 UTC, Avasam commented on Pythonwin/pywin/__init__.py
> +default_platform_encoding = "utf-8"
Indeed, not found anywhere.

2023-08-10 17:29 UTC, mhammond approved these changes
Thanks

2023-11-01 18:54 UTC, Avasam commented
> Thanks

Bumping this PR. This has been approved but not merged @mhammond

2023-11-01 19:36 UTC, merged