Fixed unbound global variables in `pywin.dialogs.ideoptions.OptionsPropPage`'s `OnFormat*` methods
mhammond/pywin32 pull request #2283
Opened 2024-06-04 23:16 UTC by Avasam

Looking at the implementation of `interact.SaveFontPreferences` this almost certainly meant to use the variables in `interact`. Although these still fail because calling `self.GetFormat` results in `AttributeError: 'PyCPropertyPage' object has no attribute 'GetFormat'`:

```py
>>> from pywin.dialogs import ideoptions; ideoptions.OptionsPropPage().OnFormatInput(None,None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python39\lib\site-packages\Pythonwin\pywin\dialogs\ideoptions.py", line 122, in OnFormatInput
    fmt = self.GetFormat(formatInput)
  File "C:\Program Files\Python39\lib\site-packages\Pythonwin\pywin\mfc\object.py", line 24, in __getattr__
    return getattr(o, attr)
AttributeError: 'PyCPropertyPage' object has no attribute 'GetFormat'
```

For all I know these methods might always have been broken in the past 25 years. At least this allows us to turn on `reportUnboundVariable` in pyright.

2024-06-04 23:24 UTC, Avasam commented on CHANGES.txt
> +* Fixed unbound global variables in `pywin.dialogs.ideoptions.OptionsPropPage`'s `OnFormat*` methods (# , @Avasam)
```suggestion
* Fixed unbound global variables in `pywin.dialogs.ideoptions.OptionsPropPage`'s `OnFormat*` methods (#2283 , @Avasam)
```

2024-10-23 21:52 UTC, Avasam commented on pyrightconfig.json
> +  "reportUndefinedVariable": "warning",
```suggestion
```

2024-11-11 16:10 UTC, mhammond requested changes
This seems fine but I don't understand why the adodbapi change is in this. This also doesn't need a changelog.

2024-11-12 00:00 UTC, mhammond approved these changes

2024-11-13 19:00 UTC, merged